import os

class Compiler:

    def build(self, architecture):

        for path in architecture["structure"]:

            os.makedirs(os.path.dirname(path), exist_ok=True)

            with open(path, "w") as f:
                f.write("# auto-generated by Agent v6\n")

        return "project compiled"
